# Generated by Django 3.0.2 on 2020-03-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescriptionChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=50)),
                ('description_changed', models.BooleanField(default=False)),
                ('date_tried', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
